version: '2.4'

services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file:
      - mongo-credentials.env
    volumes:
      - ./mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
